version: "3.9"

networks:
  kong-cdn-net:
    external: true

services:
  kong:
    image: kong:latest
    hostname: kong
    container_name: kong
    environment:
      KONG_DATABASE: 'off'
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yaml"
    volumes:
      - ./kong/config/kong.yaml:/etc/kong/kong.yaml
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    networks:
      - kong-cdn-net

  flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - kong
    networks:
      - kong-cdn-net
    volumes:
      - ./app:/app

