_format_version: "3.0"
_transform: true

services:
  - name: cdn-service
    host: cdn
    port: 5001
    protocol: http
    routes:
      - name: cdn_route
        paths:
          - /cdn
        methods:
          - GET
          - POST
        strip_path: true

  - name: app-service
    host: app
    port: 5000
    protocol: http
    routes:
      - name: app_route
        paths:
          - /app
        methods:
          - GET
          - POST
        strip_path: true

  - name: app-redirect
    host: app
    port: 5000
    protocol: http
    routes:
      - name: app_redirect_route
        paths:
          - /
        methods:
          - GET
        strip_path: true