_format_version: "3.0"
_transform: true

services:
  - name: cdn-service
    host: cdn
    port: 5001
    protocol: http
    routes:
      - name: cdn_route
        paths:
          - /cdn
        methods:
          - GET
          - POST
        strip_path: true

  - name: app-service
    host: app
    port: 5000
    protocol: http
    routes:
      - name: app_route
        paths:
          - /app
        methods:
          - GET
          - POST
        strip_path: true























# _format_version: "2.1"

# services:

#   - name: cdn-service
#     url: http://flask-app:5000
#     routes:
#       - name: cdn
#         paths:
#           - /cdn
#         methods:
#           - GET
#           - POST


# plugins:
# - name: cors
#   config: 
#     origins:
#     - "*"
#     methods:
#     - GET
#     - POST
#     headers:
#     - Accept
#     - Accept-Version
#     - Authorization
#     - Content-Length
#     - Content-MD5
#     - Content-Type
#     - Date
#     - X-Auth-Token
#     exposed_headers:
#     - X-Auth-Token
#     credentials: true
#     max_age: 3600